spring:
  banner:
    location: classpath:/banner/MikBacBanner.txt
  devtools:
    restart:
      enabled: ${DEV_TOOLS:false}
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        default_schema: ${DATABASE_SCHEMA:dependency_scanner}
  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    schemas: ${DATABASE_SCHEMA:dependency_scanner}
projects:
  scanner:
    cron: ${PROJECTS_SCANNER_CRON:0 */5 * * * *}
    batch-size: ${PROJECTS_SCANNER_BATCH_SIZE:10}
  provider:
    github:
      active: ${GITHUB_ACTIVE:true}
      url: ${GITHUB_URL:https://api.github.com/}
      token: ${GITHUB_TOKEN}
      connection-timeout: ${GITHUB_CONNECTION_TIMEOUT:30}
      read-timeout: ${GITHUB_READ_TIMEOUT:30}

resilience4j:
  circuitbreaker:
    instances:
      GitHubRepositoryDetails:
        failure-rate-threshold: 40
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10m
        permitted-number-of-calls-in-half-open-state: 4
        sliding-window-type: count_based
        sliding-window-size: 10

springdoc:
  swagger-ui:
    path: /api-docs-ui
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: ${SPRINGDOC_ENABLE:true}

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

management:
  server:
    port: 8081
  endpoint:
    prometheus:
      access: read_only
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - flyway
          - prometheus
