#
# Created by MikBac on 14.04.2024
#
version: "3.4"
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16.2
    hostname: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=dependency_status_database
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    volumes:
      - db-storage:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  db-storage:
    name: db-storage
    driver: local

networks:
  postgres-network:
