#
# Created by MikBac on 14.04.2024
#
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.2
    profiles:
      - postgres-db
    hostname: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=dependency_status_database
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    volumes:
      - db-storage:/var/lib/postgresql/data
    networks:
      - postgres-network
      - dss-network
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    profiles:
      - observability
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres1@postgres:5432/dependency_status_database?sslmode=disable"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - dss-network

volumes:
  db-storage:
    name: db-storage
    driver: local

networks:
  postgres-network:
