name: Run application tests

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests with Gradle Wrapper
        run: ./gradlew clean test
